version: '3.8'

services:
  flightsearcher:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flightsearcher
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REBROWSER_PATCHES_RUNTIME_FIX_MODE=addBinding

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - flightsearcher
